version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/recipe_api
    ports:
      - 8000:8000
    image: app:recipe_api
    container_name: recipe_api
    command: >
      sh -c "cd recipe_api &&
            python3 manage.py runserver 0.0.0.0:8000"
